### ISSUE TITLE
Update package.json exports field to provide the css file

### ISSUE THREAD

**Issue by jmltk** [jayfreestone/priority-plus#21]
Hey Jay 👋 

Yesterday I was playing around with this lib (amazing job btw!) and I noticed that Vite was complaining about the `.css` import that you state in the `README` file. Affter looking at the package.json `exports` field I saw that there's no CSS dedicated export.
Maybe in the past it used to work before defining the `exports` field but once this is present it means anything not explicitly listed inside is not exposed I guess.

Vite's complaining error:
![image](https://user-images.githubusercontent.com/118743379/213587420-84809ded-0eae-4987-a217-79a118f5aaf8.png)

Thanks so much! Let me know if you need any extra info 🙂

**Comment by jayfreestone** [comment]
Very good catch, clearly I need a test which tries to import the package 😅

Should be fixed now as of [v1.5.1](https://www.npmjs.com/package/priority-plus/v/1.5.1), lmk if not.

**Comment by jmltk** [comment]
@jayfreestone Perfectly fixed, thanks for the quick response!
