### ISSUE TITLE
Allow to customize the click handler of the more button

### ISSUE THREAD

**Issue by rastapopougros** [jayfreestone/priority-plus#6]
Didn't see that in options list, so I make an enhancement request.

The default behavior for the More button is just to open/unfold an other menu containing hidden items. No change for that.

But some times, we want more complicated behavior, for example if we want to open a totally other menu than just the 2 or 3 hidden items, like a full sliding menu, or a fullscreen menu.

The simple way to allow that would be an option to pass a function which will overload the default handler. Like "buttonHandler" for ex, or "onToggleClick" to follow your current code.

The current "onToggleClick" could be rename as "onToggleClickDefault" and an option "onToggleClick" will wait a function, and trigger that if defined, else the default one.

Very simple, but one more customization possible! :)

**Comment by jayfreestone** [comment]
Hi @rastapopougros, just wanted to check if you feel PR https://github.com/jayfreestone/priority-plus/pull/7 covers this use-case well enough?
