### ISSUE TITLE
Don't remove original classes and attributes

### ISSUE THREAD

**Issue by rastapopougros** [jayfreestone/priority-plus#8]
Hello, 
finally find some time to start using and testing, and I have a huge problem using in the context of a CMS, or any dynamically generated content.

My menu is genereted dynamically too, with many informations on each entries, mostly via class names (but also data-attributes !). So on any "ul" and "li" there are class saying "this entry will point on an article/a category/an event/etc" or also "this entry is active, because it's part of the breadcrumb of the current page (like one of parent category)", etc.

Real life examples : 
```html
<ul class="menu-items" data-depth="1">
    <li class="menu-items__item menu-items__item_article menu-items__item_active">
        <a href="link to an article">
```

And all my themes will take all those classes and attributes in account to adjust styles, obviously.

But… this lib rewrite absolutely all top entries ! With own HTML and CSS classes, and only that, removing all the original ones (classes but also attributes). Sub-entries (when there is sub-menus, dropdown menus, etc) remain the sames, the rewriting is only for top entries.

The solution seems simple (I hope): the lib must never change the original code but only add its own classes, never removing which exist (any attributes).

**Comment by jayfreestone** [comment]
@rastapopougros 

Yep, good point, no attempt is currently made to preserve any of the original classes or attributes.

I guess the question is: is it enough to create identical clones of the originals, or do the nodes actually need to be the same? The effect should be similar, but event listeners applied to the originals won't carry over to the clones. Reusing the existing nodes is a little harder since it complicates the reversion process in `destroy()` (which currently just re-instates the old tree).

I've created a PR and, although it probably needs a once over, I think it at least satisfies the requirements of keeping the original classes/attributes.

**Comment by rastapopougros** [comment]
Oh yes, very good question, for the clones…

For CSS, it doesn't matter, styles will be applied and the menu will be display gracefully, clone or not.

But yes, they totally could be linked with JS behaviour  (for opening sub menu, or any other needs), so… it will break that, arg.

For example: with the previous priority lib I was using, I used *also* [the accessibility menu lib by adobe](https://github.com/adobe-accessibility/Accessible-Mega-Menu). This lib helps to have a multi-level menu totally accessible, adding aria attributes + adding very good keyboard navigation. My usage was using this accessible lib + reduce the top entries with priority-nav when not enough space.
(But it's just one example, I suppose we could imagine many other usages where we attach behaviour to original nodes of the menu.)

**Comment by jayfreestone** [comment]
I'm tempted to just keep the clones and add an additional `init` event for when the library swaps out the elements. Then if you do want to add additional listeners/libraries, it's possible, they just need to be registered afterwards:

```javascript
const target = document.querySelector('.js-p-target');
const inst = priorityPlus(target);
inst.on('init', () => loadLibrary(target));
```

It keeps the implementation simple for now, and if it does turn out to be an annoyance later then we can always revisit.
